name: StillpointSF
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48556
title: Stillpoint Wellness Center
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#979797'
    - '#2a3a8f'
    - '#26a9e1'
    - '#5f61a9'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
